Develop
cos-labs/share-analytics pull request #9
Opened 2016-11-23 22:12 UTC by 545zhou

2016-11-29 15:09 UTC, NyanHelsing requested changes

2016-11-29 15:09 UTC, HalcyonChimera commented on client/app/models/widget.js
> +    query: attr({
I think query needs to be just passed through as is. If a different object is stored in this field right now, it probably won't validate. Query here would be the whole data that gets posted. Maybe its better to rename this to request_data or something that is clearer.

2016-11-29 15:09 UTC, HalcyonChimera commented on client/app/models/widget.js
> +    settings: attr({
Same should go for settings. This would be settings for the chart.

2016-11-30 19:10 UTC, NyanHelsing approved these changes

2016-12-01 20:51 UTC, 545zhou commented
could check the new changes?

2016-12-01 23:02 UTC, NyanHelsing approved these changes

2016-12-02 21:40 UTC, closed without merging